import { Task } from './task';

export const TASKS: Task[] = [
  { id: 1, descr: 'Reduce churn to <5% annually through customer success', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 2, descr: 'Increase positive feedback items and praise from 5 to 15 per quarter', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 3, descr: 'Create & launch new mentorship program by the end of Q3', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 4, descr: 'Win 1,000 deals worth $10M in bookings by 12/31/17', status: 'Need help', color: { tag: '#212132', bg: '#2121321A' } },
  { id: 5, descr: 'Exceed Net Promoter Score (NPS) of over 8.0', status: 'Need help', color: { tag: '#212132', bg: '#2121321A' } },
  { id: 6, descr: 'Decrease number of complaints and negative feedback per quarter from 15 to 5', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 7, descr: 'Interview 20 customers per month and get feedback', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 8, descr: 'Get 1000 survey responses to annual satisfaction survey', status: 'Off track', color: { tag: '#FF525C', bg: '#FFE6EB' } },
  { id: 9, descr: 'Hit company global sales target of $100 Million in Sales', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 10, descr: 'Set budget for design software, online presence accounts (like Dribbble), and premium resources that make no sense to create ourselves (mockup templates, wireframe kits, stock photos and illustrations)', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },

  { id: 11, descr: '11 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 12, descr: '12 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 13, descr: '13 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 14, descr: '14 - Some description here', status: 'Need help', color: { tag: '#212132', bg: '#2121321A' } },
  { id: 15, descr: '15 - Some description here', status: 'Need help', color: { tag: '#212132', bg: '#2121321A' } },
  { id: 16, descr: '16 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 17, descr: '17 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 18, descr: '18 - Some description here', status: 'Off track', color: { tag: '#FF525C', bg: '#FFE6EB' } },
  { id: 19, descr: '19 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 20, descr: '20 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },

  { id: 21, descr: '21 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 22, descr: '22 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 23, descr: '23 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 24, descr: '24 - Some description here', status: 'Need help', color: { tag: '#212132', bg: '#2121321A' } },
  { id: 25, descr: '25 - Some description here', status: 'Need help', color: { tag: '#212132', bg: '#2121321A' } },
  { id: 26, descr: '26 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 27, descr: '27 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 28, descr: '28 - Some description here', status: 'Off track', color: { tag: '#FF525C', bg: '#FFE6EB' } },
  { id: 29, descr: '29 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
  { id: 30, descr: '30 - Some description here', status: 'On track', color: { tag: '#C5DE5D', bg: '#F2F7DA' } },
];
